#pragma checksum "..\..\DodavanjeK.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "58066B1AAD813ABC27B41077B9B9300DE66B3BE88F19AEB906BE9E6EC8E98F9C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using Pilana123;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Pilana123 {
    
    
    /// <summary>
    /// DodavanjeK
    /// </summary>
    public partial class DodavanjeK : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 29 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Ime;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Prezime;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Adresa;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Kontakt;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PIB;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox JMBG;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\DodavanjeK.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button Dodaj;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Pilana123;component/dodavanjek.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\DodavanjeK.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\DodavanjeK.xaml"
            ((Pilana123.DodavanjeK)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.UserControl_IsVisibleChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.Ime = ((System.Windows.Controls.TextBox)(target));
            
            #line 29 "..\..\DodavanjeK.xaml"
            this.Ime.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Ime_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 29 "..\..\DodavanjeK.xaml"
            this.Ime.LostFocus += new System.Windows.RoutedEventHandler(this.Ime_LostFocus);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Prezime = ((System.Windows.Controls.TextBox)(target));
            
            #line 30 "..\..\DodavanjeK.xaml"
            this.Prezime.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Prezime_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 30 "..\..\DodavanjeK.xaml"
            this.Prezime.LostFocus += new System.Windows.RoutedEventHandler(this.Prezime_LostFocus);
            
            #line default
            #line hidden
            return;
            case 4:
            this.Adresa = ((System.Windows.Controls.TextBox)(target));
            
            #line 31 "..\..\DodavanjeK.xaml"
            this.Adresa.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Adresa_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 31 "..\..\DodavanjeK.xaml"
            this.Adresa.LostFocus += new System.Windows.RoutedEventHandler(this.Adresa_LostFocus);
            
            #line default
            #line hidden
            return;
            case 5:
            this.Kontakt = ((System.Windows.Controls.TextBox)(target));
            
            #line 32 "..\..\DodavanjeK.xaml"
            this.Kontakt.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Kontakt_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 32 "..\..\DodavanjeK.xaml"
            this.Kontakt.GotFocus += new System.Windows.RoutedEventHandler(this.Kontakt_GotFocus);
            
            #line default
            #line hidden
            
            #line 32 "..\..\DodavanjeK.xaml"
            this.Kontakt.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Kontakt_TextChanged);
            
            #line default
            #line hidden
            
            #line 32 "..\..\DodavanjeK.xaml"
            this.Kontakt.LostFocus += new System.Windows.RoutedEventHandler(this.Kontakt_LostFocus);
            
            #line default
            #line hidden
            return;
            case 6:
            this.PIB = ((System.Windows.Controls.TextBox)(target));
            
            #line 33 "..\..\DodavanjeK.xaml"
            this.PIB.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.PIB_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 33 "..\..\DodavanjeK.xaml"
            this.PIB.LostFocus += new System.Windows.RoutedEventHandler(this.PIB_LostFocus);
            
            #line default
            #line hidden
            return;
            case 7:
            this.JMBG = ((System.Windows.Controls.TextBox)(target));
            
            #line 34 "..\..\DodavanjeK.xaml"
            this.JMBG.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.JMBG_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 34 "..\..\DodavanjeK.xaml"
            this.JMBG.LostFocus += new System.Windows.RoutedEventHandler(this.JMBG_LostFocus);
            
            #line default
            #line hidden
            return;
            case 8:
            this.Dodaj = ((System.Windows.Controls.Button)(target));
            
            #line 36 "..\..\DodavanjeK.xaml"
            this.Dodaj.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Dodaj_MouseEnter);
            
            #line default
            #line hidden
            
            #line 36 "..\..\DodavanjeK.xaml"
            this.Dodaj.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Dodaj_MouseLeave);
            
            #line default
            #line hidden
            
            #line 36 "..\..\DodavanjeK.xaml"
            this.Dodaj.Click += new System.Windows.RoutedEventHandler(this.Dodaj_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

