#pragma checksum "..\..\GlavniMeni.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C19E28B90B1162F740E52FF600692DC73002C79BB59F33438FA6E26970D5E639"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using Pilana123;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Pilana123 {
    
    
    /// <summary>
    /// GlavniMeni
    /// </summary>
    public partial class GlavniMeni : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 28 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Home;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Klijenti;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem DodavanjeKlijenata;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem TabelaKlijenata;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Porudzbenice;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Uizradi;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Ponude;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem KreiranjePonude;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem TabelaPonuda;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Fakture;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem KreiranjeFakture;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem TabelaFaktura;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Otpremnice;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem KreiranjeOtpremnice;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem TabelaOtpremnica;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Pomoc;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem About;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Help;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem Odjava;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image Logo;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.DodavanjeK DodavanjeK;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.TabelaK TabelaK;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.KreiranjeP KreiranjeP;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.TabelaP TabelaP;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.KreiranjeF KreiranjeF;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.TabelaF TabelaF;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.KreiranjeO KreiranjeO;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\GlavniMeni.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Pilana123.TabelaO TabelaO;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Pilana123;component/glavnimeni.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\GlavniMeni.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 16 "..\..\GlavniMeni.xaml"
            ((Pilana123.GlavniMeni)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Window_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.Home = ((System.Windows.Controls.MenuItem)(target));
            
            #line 28 "..\..\GlavniMeni.xaml"
            this.Home.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Home_MouseEnter);
            
            #line default
            #line hidden
            
            #line 28 "..\..\GlavniMeni.xaml"
            this.Home.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Home_MouseLeave);
            
            #line default
            #line hidden
            
            #line 28 "..\..\GlavniMeni.xaml"
            this.Home.Click += new System.Windows.RoutedEventHandler(this.Uizradi_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Klijenti = ((System.Windows.Controls.MenuItem)(target));
            
            #line 29 "..\..\GlavniMeni.xaml"
            this.Klijenti.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Klijenti_MouseEnter);
            
            #line default
            #line hidden
            
            #line 29 "..\..\GlavniMeni.xaml"
            this.Klijenti.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Klijenti_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 4:
            this.DodavanjeKlijenata = ((System.Windows.Controls.MenuItem)(target));
            
            #line 30 "..\..\GlavniMeni.xaml"
            this.DodavanjeKlijenata.Click += new System.Windows.RoutedEventHandler(this.DodavanjeKlijenata_Click);
            
            #line default
            #line hidden
            
            #line 30 "..\..\GlavniMeni.xaml"
            this.DodavanjeKlijenata.MouseEnter += new System.Windows.Input.MouseEventHandler(this.DodavanjeKlijenata_MouseEnter);
            
            #line default
            #line hidden
            
            #line 30 "..\..\GlavniMeni.xaml"
            this.DodavanjeKlijenata.MouseLeave += new System.Windows.Input.MouseEventHandler(this.DodavanjeKlijenata_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TabelaKlijenata = ((System.Windows.Controls.MenuItem)(target));
            
            #line 36 "..\..\GlavniMeni.xaml"
            this.TabelaKlijenata.Click += new System.Windows.RoutedEventHandler(this.TabelaKlijenata_Click);
            
            #line default
            #line hidden
            
            #line 36 "..\..\GlavniMeni.xaml"
            this.TabelaKlijenata.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TabelaKlijenata_MouseEnter);
            
            #line default
            #line hidden
            
            #line 36 "..\..\GlavniMeni.xaml"
            this.TabelaKlijenata.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TabelaKlijenata_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Porudzbenice = ((System.Windows.Controls.MenuItem)(target));
            
            #line 43 "..\..\GlavniMeni.xaml"
            this.Porudzbenice.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Porudzbenice_MouseEnter);
            
            #line default
            #line hidden
            
            #line 43 "..\..\GlavniMeni.xaml"
            this.Porudzbenice.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Porudzbenice_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 7:
            this.Uizradi = ((System.Windows.Controls.MenuItem)(target));
            
            #line 44 "..\..\GlavniMeni.xaml"
            this.Uizradi.Click += new System.Windows.RoutedEventHandler(this.Uizradi_Click);
            
            #line default
            #line hidden
            
            #line 44 "..\..\GlavniMeni.xaml"
            this.Uizradi.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Uizradi_MouseEnter);
            
            #line default
            #line hidden
            
            #line 44 "..\..\GlavniMeni.xaml"
            this.Uizradi.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Uizradi_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 8:
            this.Ponude = ((System.Windows.Controls.MenuItem)(target));
            
            #line 51 "..\..\GlavniMeni.xaml"
            this.Ponude.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Ponude_MouseEnter);
            
            #line default
            #line hidden
            
            #line 51 "..\..\GlavniMeni.xaml"
            this.Ponude.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Ponude_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 9:
            this.KreiranjePonude = ((System.Windows.Controls.MenuItem)(target));
            
            #line 52 "..\..\GlavniMeni.xaml"
            this.KreiranjePonude.Click += new System.Windows.RoutedEventHandler(this.KreiranjePonuda_Click);
            
            #line default
            #line hidden
            
            #line 52 "..\..\GlavniMeni.xaml"
            this.KreiranjePonude.MouseEnter += new System.Windows.Input.MouseEventHandler(this.KreiranjePonude_MouseEnter);
            
            #line default
            #line hidden
            
            #line 52 "..\..\GlavniMeni.xaml"
            this.KreiranjePonude.MouseLeave += new System.Windows.Input.MouseEventHandler(this.KreiranjePonude_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 10:
            this.TabelaPonuda = ((System.Windows.Controls.MenuItem)(target));
            
            #line 58 "..\..\GlavniMeni.xaml"
            this.TabelaPonuda.Click += new System.Windows.RoutedEventHandler(this.TabelaPonuda_Click);
            
            #line default
            #line hidden
            
            #line 58 "..\..\GlavniMeni.xaml"
            this.TabelaPonuda.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TabelaPonuda_MouseEnter);
            
            #line default
            #line hidden
            
            #line 58 "..\..\GlavniMeni.xaml"
            this.TabelaPonuda.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TabelaPonuda_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 11:
            this.Fakture = ((System.Windows.Controls.MenuItem)(target));
            
            #line 65 "..\..\GlavniMeni.xaml"
            this.Fakture.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Fakture_MouseEnter);
            
            #line default
            #line hidden
            
            #line 65 "..\..\GlavniMeni.xaml"
            this.Fakture.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Fakture_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 12:
            this.KreiranjeFakture = ((System.Windows.Controls.MenuItem)(target));
            
            #line 66 "..\..\GlavniMeni.xaml"
            this.KreiranjeFakture.Click += new System.Windows.RoutedEventHandler(this.KreiranjeFaktura_Click);
            
            #line default
            #line hidden
            
            #line 66 "..\..\GlavniMeni.xaml"
            this.KreiranjeFakture.MouseEnter += new System.Windows.Input.MouseEventHandler(this.KreiranjeFakture_MouseEnter);
            
            #line default
            #line hidden
            
            #line 66 "..\..\GlavniMeni.xaml"
            this.KreiranjeFakture.MouseLeave += new System.Windows.Input.MouseEventHandler(this.KreiranjeFakture_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 13:
            this.TabelaFaktura = ((System.Windows.Controls.MenuItem)(target));
            
            #line 72 "..\..\GlavniMeni.xaml"
            this.TabelaFaktura.Click += new System.Windows.RoutedEventHandler(this.TabelaFaktura_Click);
            
            #line default
            #line hidden
            
            #line 72 "..\..\GlavniMeni.xaml"
            this.TabelaFaktura.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TabelaFaktura_MouseEnter);
            
            #line default
            #line hidden
            
            #line 72 "..\..\GlavniMeni.xaml"
            this.TabelaFaktura.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TabelaFaktura_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 14:
            this.Otpremnice = ((System.Windows.Controls.MenuItem)(target));
            
            #line 79 "..\..\GlavniMeni.xaml"
            this.Otpremnice.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Otpremnice_MouseEnter);
            
            #line default
            #line hidden
            
            #line 79 "..\..\GlavniMeni.xaml"
            this.Otpremnice.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Otpremnice_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 15:
            this.KreiranjeOtpremnice = ((System.Windows.Controls.MenuItem)(target));
            
            #line 80 "..\..\GlavniMeni.xaml"
            this.KreiranjeOtpremnice.Click += new System.Windows.RoutedEventHandler(this.KreiranjeOtpremnica_Click);
            
            #line default
            #line hidden
            
            #line 80 "..\..\GlavniMeni.xaml"
            this.KreiranjeOtpremnice.MouseEnter += new System.Windows.Input.MouseEventHandler(this.KreiranjeOtpremnice_MouseEnter);
            
            #line default
            #line hidden
            
            #line 80 "..\..\GlavniMeni.xaml"
            this.KreiranjeOtpremnice.MouseLeave += new System.Windows.Input.MouseEventHandler(this.KreiranjeOtpremnice_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 16:
            this.TabelaOtpremnica = ((System.Windows.Controls.MenuItem)(target));
            
            #line 86 "..\..\GlavniMeni.xaml"
            this.TabelaOtpremnica.Click += new System.Windows.RoutedEventHandler(this.TabelaOtpremnica_Click);
            
            #line default
            #line hidden
            
            #line 86 "..\..\GlavniMeni.xaml"
            this.TabelaOtpremnica.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TabelaOtpremnica_MouseEnter);
            
            #line default
            #line hidden
            
            #line 86 "..\..\GlavniMeni.xaml"
            this.TabelaOtpremnica.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TabelaOtpremnica_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 17:
            this.Pomoc = ((System.Windows.Controls.MenuItem)(target));
            
            #line 93 "..\..\GlavniMeni.xaml"
            this.Pomoc.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Pomoc_MouseEnter);
            
            #line default
            #line hidden
            
            #line 93 "..\..\GlavniMeni.xaml"
            this.Pomoc.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Pomoc_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 18:
            this.About = ((System.Windows.Controls.MenuItem)(target));
            
            #line 94 "..\..\GlavniMeni.xaml"
            this.About.Click += new System.Windows.RoutedEventHandler(this.About_Click);
            
            #line default
            #line hidden
            
            #line 94 "..\..\GlavniMeni.xaml"
            this.About.MouseEnter += new System.Windows.Input.MouseEventHandler(this.About_MouseEnter);
            
            #line default
            #line hidden
            
            #line 94 "..\..\GlavniMeni.xaml"
            this.About.MouseLeave += new System.Windows.Input.MouseEventHandler(this.About_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 19:
            this.Help = ((System.Windows.Controls.MenuItem)(target));
            
            #line 100 "..\..\GlavniMeni.xaml"
            this.Help.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Help_MouseEnter);
            
            #line default
            #line hidden
            
            #line 100 "..\..\GlavniMeni.xaml"
            this.Help.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Help_MouseLeave);
            
            #line default
            #line hidden
            
            #line 100 "..\..\GlavniMeni.xaml"
            this.Help.Click += new System.Windows.RoutedEventHandler(this.Help_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.Odjava = ((System.Windows.Controls.MenuItem)(target));
            
            #line 107 "..\..\GlavniMeni.xaml"
            this.Odjava.Click += new System.Windows.RoutedEventHandler(this.Odjava_Click);
            
            #line default
            #line hidden
            
            #line 107 "..\..\GlavniMeni.xaml"
            this.Odjava.MouseEnter += new System.Windows.Input.MouseEventHandler(this.Odjava_MouseEnter);
            
            #line default
            #line hidden
            
            #line 107 "..\..\GlavniMeni.xaml"
            this.Odjava.MouseLeave += new System.Windows.Input.MouseEventHandler(this.Odjava_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 21:
            this.Logo = ((System.Windows.Controls.Image)(target));
            return;
            case 22:
            this.DodavanjeK = ((Pilana123.DodavanjeK)(target));
            return;
            case 23:
            this.TabelaK = ((Pilana123.TabelaK)(target));
            return;
            case 24:
            this.KreiranjeP = ((Pilana123.KreiranjeP)(target));
            return;
            case 25:
            this.TabelaP = ((Pilana123.TabelaP)(target));
            return;
            case 26:
            this.KreiranjeF = ((Pilana123.KreiranjeF)(target));
            return;
            case 27:
            this.TabelaF = ((Pilana123.TabelaF)(target));
            return;
            case 28:
            this.KreiranjeO = ((Pilana123.KreiranjeO)(target));
            return;
            case 29:
            this.TabelaO = ((Pilana123.TabelaO)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

